### ISSUE TITLE
复现精度

### ISSUE THREAD

**Issue by songyonger** [colorjam/PAMS#15]
您好，我按照run.sh中命令进行训练，8bit，patch_size取192，scale取4时，训练30个epoch，在Set14上的PSNR为28.174dB，和您论文里的28.585dB相差很大，请问这是什么原因呢？

**Comment by zysxmu** [comment]
Hi, do you solve this problem?

**Comment by songyonger** [comment]
没有，感觉论文里所说训练30个epoch有点奇怪

**Comment by zysxmu** [comment]
OK, thank you very much. I will try more epochs and report the results.

**Comment by zysxmu** [comment]
Hi, the result can be reproduced when 1) load the pre-trained parameters (in this code, the pre-trained parameters are overlooked) and 2) train 60 epoch.

**Comment by Sheldon04** [comment]
Hi, zysxmu, I want to know that how to load the pre-trained parameters as you said. Could you give me some help?

**Comment by Sheldon04** [comment]
Hi, zysxmu, I want to know that how to load the pre-trained parameters as you said. Could you give me some help?

**Comment by zysxmu** [comment]
> Hi, zysxmu, I want to know that how to load the pre-trained parameters as you said. Could you give me some help?

Hi, you can go here to find some inspirations: 
https://github.com/zysxmu/DDTB/blob/main/main_limitrange_incremental.py
lines 370-404
