### ISSUE TITLE
Training Error

### ISSUE THREAD

**Issue by huangqiu15444** [colorjam/PAMS#2]
![image](https://user-images.githubusercontent.com/38499268/101358951-8cb8a500-38d6-11eb-8789-4556767d6c7b.png)

Thank you for sharing your excellent work. I got a problem when network training.

**Comment by colorjam** [comment]
@huangqiu15444 hi, did you download the DIV2k datasets, and modify the `$DATA_DIR` to the correct path in`run.sh`?
