### ISSUE TITLE
Something confused in quant_ops.py

### ISSUE THREAD

**Issue by Liang-ZX** [colorjam/PAMS#9]
The variable ```self.epoch``` seems to be constant **1**, and then the ```self._ema()``` function would not work well.

**Comment by colorjam** [comment]
Hi @Liang-ZX , please refer to the answer of issue https://github.com/colorjam/PAMS/issues/5

**Comment by Liang-ZX** [comment]
Thanks for sharing your excellent work!

**Comment by Liang-ZX** [comment]
Thanks for sharing your excellent work!
